[package]
name = "rust"
version = "0.1.0"
edition = "2024"

[dependencies]
rocket = { version = "0.5.1", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }

[[bin]]
edition = "2021" # лучше обновить до 2021
name = "test"
path = "src/main.rs"